MODEL:
  TYPE: resnet50
  NAME: resnet50_finetune
  NUM_CLASSES: 2
  DROP_RATE: 0.20
  DROP_PATH_RATE: 0.0
  LABEL_SMOOTHING: 0.10

DATA:
  IMG_SIZE: 224

TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 5
  BASE_LR: 3.2e-3
  WARMUP_LR: 3.2e-5
  MIN_LR: 3.2e-6
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 1.0
  AUTO_RESUME: False

PRINT_FREQ: 100
SAVE_FREQ: 50
TAG: resnet50_finetune_img224
