# MODEL:
#   TYPE: dinov2
#   NAME: dinov2_vits14_finetune
#   NUM_CLASSES: 2
#   DROP_RATE: 0.2
#   DROP_PATH_RATE: 0.0
#   LABEL_SMOOTHING: 0.1
#   RESUME: ""

# DATA:
#   BATCH_SIZE: 8
#   DATA_PATH: ""
#   DATASET: imagenet
#   IMG_SIZE: 224
#   INTERPOLATION: bicubic
#   NUM_WORKERS: 8
#   PIN_MEMORY: true

# TRAIN:
#   START_EPOCH: 0
#   EPOCHS: 10
#   WARMUP_EPOCHS: 1
#   WEIGHT_DECAY: 0.05
#   BASE_LR: 0.00005
#   WARMUP_LR: 0.0000005
#   MIN_LR: 0.00000005
#   CLIP_GRAD: 5.0
#   AUTO_RESUME: false
#   ACCUMULATION_STEPS: 0
#   USE_CHECKPOINT: false

#   LR_SCHEDULER:
#     NAME: cosine
#     DECAY_EPOCHS: 30
#     DECAY_RATE: 0.1
#     GAMMA: 0.1
#     MULTISTEPS: []

#   OPTIMIZER:
#     NAME: adamw
#     EPS: 0.00000001
#     BETAS:
#       - 0.9
#       - 0.999
#     MOMENTUM: 0.9

# AUG:
#   COLOR_JITTER: 0.2
#   AUTO_AUGMENT: rand-m5-mstd0.5-inc1
#   REPROB: 0.1
#   REMODE: pixel
#   RECOUNT: 1
#   MIXUP: 0.2
#   MIXUP_PROB: 0.5
#   MIXUP_SWITCH_PROB: 0.5
#   MIXUP_MODE: batch
#   CUTMIX: 0.2
#   CUTMIX_MINMAX: null

# TEST:
#   CROP: true

# AMP_OPT_LEVEL: O0
# OUTPUT: output
# TAG: default
# SAVE_FREQ: 25
# PRINT_FREQ: 100
# SEED: 0
# EVAL_MODE: false
# THROUGHPUT_MODE: false
# LOCAL_RANK: 0


MODEL:
  TYPE: dinov2
  NAME: dinov2_vits14_finetune
  NUM_CLASSES: 2

  # stronger regularization
  DROP_RATE: 0.35
  DROP_PATH_RATE: 0.25
  LABEL_SMOOTHING: 0.25

  RESUME: ""


DATA:
  BATCH_SIZE: 8
  DATA_PATH: ""
  DATASET: imagenet
  IMG_SIZE: 224
  INTERPOLATION: bicubic
  NUM_WORKERS: 8
  PIN_MEMORY: true


TRAIN:
  START_EPOCH: 0

  # long training
  EPOCHS: 100
  WARMUP_EPOCHS: 8

  WEIGHT_DECAY: 0.15

  # lower lr for pretrained backbone
  BASE_LR: 0.00003
  WARMUP_LR: 0.0000003
  MIN_LR: 0.000000003

  CLIP_GRAD: 2.0

  AUTO_RESUME: false
  ACCUMULATION_STEPS: 0
  USE_CHECKPOINT: false


  LR_SCHEDULER:
    NAME: cosine
    DECAY_EPOCHS: 30
    DECAY_RATE: 0.1
    GAMMA: 0.1
    MULTISTEPS: []


  OPTIMIZER:
    NAME: adamw
    EPS: 0.00000001

    BETAS:
      - 0.9
      - 0.999

    MOMENTUM: 0.9



AUG:
  # stronger augmentation
  COLOR_JITTER: 0.45

  AUTO_AUGMENT:
    rand-m9-mstd0.5-inc1

  REPROB: 0.35

  REMODE: pixel
  RECOUNT: 1


  # stronger mixing
  MIXUP: 0.45
  MIXUP_PROB: 0.8
  MIXUP_SWITCH_PROB: 0.5
  MIXUP_MODE: batch

  CUTMIX: 0.45
  CUTMIX_MINMAX: null



TEST:
  CROP: true


AMP_OPT_LEVEL: O0

OUTPUT:
  output

TAG:
  dinov2_vits14_strong_reg_100ep


SAVE_FREQ:
  5

PRINT_FREQ:
  100

SEED:
  0

EVAL_MODE:
  false

THROUGHPUT_MODE:
  false

LOCAL_RANK:
  0











# cd /home/administrator/SimMIM-main

# torchrun --standalone --nproc_per_node=1 \
# gradcam_balanced_dinov2.py \
# --cfg ./configs/dinov2/dinov2_vits14_finetune_img224.yaml \
# --data-path /home/administrator/DFD-SCRM-main/data/UTA-RLDD \
# --batch-size 8 \
# --amp-opt-level O0 \
# --dinov2-model dinov2_vits14 \
# --skip-gradcam \
# --tag uta_rldd_dinov2_vits14_10ep \
# --opts \
# TRAIN.EPOCHS 10 \
# TRAIN.WARMUP_EPOCHS 1 \
# TRAIN.AUTO_RESUME False

